export const GET_DATA= "GET_PORTFOLIO"
export const CREATE_DATA= "CREATE_PORTFOLIO"
export const UPDATE_DATA= "UPDATE_PORTFOLIO"
export const DELETE_DATA= "DELETE_PORTFOLIO_IMG"
export const MESSAGE = "PORTFOLIO_MESSAGE";