export const GET_DATA= "GET_ABOUT"
export const CREATE_DATA= "CREATE_ABOUT"
export const UPDATE_DATA= "UPDATE_ABOUT"
export const DELETE_DATA_IMG= "DELETE_ABOUT_IMG"
export const MESSAGE = "ABOUT_MESSAGE";

export const GET_DATA_LISTING= "GET_ABOUT_LISTING"
export const CREATE_DATA_LISTING= "CREATE_ABOUT_LISTING"
export const UPDATE_DATA_LISTING= "UPDATE_ABOUT_LISTING"
export const DELETE_DATA_LISTING= "DELETE_ABOUT_LISTING"